spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false   # 개발 시 필수
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:0.5b
