spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false   # 개발 시 필수
  ai:
    openai:
      api-key: 개인 API 키 입력
      chat:
        options:
          model: gpt-4.1-mini
          temperature: 0.7
          max-tokens: 800
